### PR TITLE
New readme

### PR DESCRIPTION
**Pull request by theRealImy**

### CODE REVIEW

**Comment by TallTed** [comment]
Please leave non-trivial PRs open for review for at least a business day, preferably longer, especially for changes of this size.  There are multiple punctuation and other issues in this PR, and it will take considerably more time and effort to fix them with another PR than it would have with change requests on this PR.

**Comment by theRealImy** [comment]
I would agree with you except that this was ongoing for over a month and there was a dedicated week for additional changes. All these were discussed and agreed upon in the SolidOS team meetings. 
Regarding the quality: I am not a native speaker so I used a grammatical checking tool. I did my best. 
If you want to improve it you can make a PR to main or you can work on the https://github.com/solid/solidos/tree/newReadme branch. I do not mind the extra work of merging and so.  Next time maybe we can do it better, in a better collaborative manner. 
Would you want to join our team meetings? 
We now put our team meeting minutes not only in the solidos gitter channel but also on: https://solidos.solidcommunity.net/public/SolidOS%20team%20meetings/

**Comment by TallTed** [comment]
The preparation of this PR may well have been ongoing for over a month on some branch or fork out there. The commits that make it up, likewise. But the PR itself was not raised on the `main` branch until immediately (certainly within an hour, possibly only minutes) before it was merged. The point of PRs is to give people other than its author a chance to raise concerns before it gets merged; else, the changes could just be merged directly and immediately.

Further, I submitted [a PR against the newReadme branch a week ago, on Nov 5](https://github.com/solid/solidos/pull/87), which long pre-dated the [commits of Nov 11 & 12](https://github.com/solid/solidos/commits/newReadme/README.md) which resulted in the now-extant merge conflicts, which I now have extra work to resolve.  Why was that PR ignored?

As to Gitter -- I cannot speak for others, but certainly for myself, there are too many Gitter channels, with far too much chatter, to actively keep up with, while also keeping up with $dayjob duties, which invariably include keeping up with numerous Slack and IRC and sometimes Gitter channels, GitHub and GitLab and other repos, Discourse and PHPBB and other forums, mailing lists, and the like.

As to joining meetings -- I see minutes for 2021-11-03 and 2021-11-10 in the [directory you linked](https://solidos.solidcommunity.net/public/SolidOS%20team%20meetings/), but where is the schedule of future events?  Best practice for meeting agendas & minutes is to include: a link to the minutes of the previous meeting in both agenda and minutes (which documents may be distinct or conjoined) of the current/latest meeting; and a link to the agenda of the current/latest meeting along with a link to the agenda for the next meeting (including at least its planned date-time [optimally with a link to the worldclock, to avoid timezone confusion] and other details for joining, even if most of that agenda is just boilerplate to start with) in the minutes of the current/latest meeting.

**Comment by theRealImy** [comment]
Thank you for your corrections! 
I am truly sorry I did not see your PR you mentioned 😅. It was completely my mistake since I was the only one working on the branch.
Thank you also for the feedback on the meeting template. I either overlooked that aspect or it was missing in the w3c template. In any case, it does not matter, I shall improve it. 
Now that I am aware that there are active contributors who are not in the chat and meetings, I will adjust my way of working and be more considerate.

**Pull request merged**
