### PR TITLE
Update SolidOS README.md

### PR DESCRIPTION
**Pull request by bourgeoa**
I'm not so happy with the access to Documentation in the different repos.
This came because I was looking for some and also the forum discussion https://forum.solidproject.org/t/is-rdf-hard/5056?u=bourgeoa introducing a Developer Relations question.
May be we could consider either :
- a wiki page SolidOS documentation
- or in github.com/dolid/solidos/Documentation

with links to all types of documentation :
- SolidOS general presentation (talks, videos)
- API (rdflib, solid-ui)
- technical (style, developers recommendations)
- data models and ontologies
- demos

### CODE REVIEW

**Review by theRealImy — APPROVED** [review]

**Comment by ewingson** [comment]
@theRealImy 
`<text>`
momentary I am working on https://github.com/ewingson/solid-file-client/tree/use_dpop_auth.
I shall look into the SolidOS code and *understand* the processes.
perfect would be a *very* small task, like for example add a textfield or add a formular field/entry on e.g. the profile page.
I have a SolidOS fork but it's not up-to-date.
the solid-file-client-demo is a perfect start, cause I get used to
- git status
- git add
- git status
- git commit
- git status
- git push

we/you/me could assign myself a documentation task as e.g. gather some links as for example in https://serverproject.de/t7/index.php?id=9 but group them with meaningful headlines.
`</text>`

**Comment by bourgeoa** [comment]
@ewingson gathering and grouping links what the work proposed by @theRealImy

a wiki page SolidOS documentation so we can all work on it.
with links to all types of documentation :

- SolidOS general presentation (talks, videos)
- API (rdflib, solid-ui)
- technical (style, developers recommendations)
- data models and ontologies
- demos

**Comment by ewingson** [comment]
https://github.com/solid/solidos/wiki already exists ... ?
shall we improve or start over new at another URL ?

**Comment by ewingson** [comment]
I think that's great work, so let's just improve it.
maybe collecting links at a secondary resource (solidproject.solidcommunity.net for example) ...

**Comment by bourgeoa** [comment]
I opened a page https://github.com/solid/solidos/wiki/SolidOS-documentation
You can work freely on this one.
Please do not edit the other pages for the time being.

**Pull request merged**
